---
# tasks file for cobbler
#
- name: Install cobbler 
  yum: name={{ item }} state=latest
  with_items:
    - cobbler-web
    - cobbler
    - httpd

- name: Start and enable services 
  service: name={{ item }} enabled=yes state=restarted
  with_items:
    - cobblerd
    - httpd

- name: Set initial password for cobbler
  lineinfile: dest=/etc/cobbler/users.digest line="admin:Cobbler:f26a7a35c3c161e294f6b12c4b65e139" 

- name: Configure the repos
  command: cobbler repo add --name={{ item.key }} --mirror={{ item.value }}
  with_dict:
    epel-7-x86_64: http://download.fedoraproject.org/pub/epel/7/x86_64 
    CentOS-7-Base: http://mirror.centos.org/centos/7/os/x86_64/
    CentOS-7-Updates: http://mirror.centos.org/centos/7/updates/x86_64/
    CentOS-7-Extras: http://mirror.centos.org/centos/7/extras/x86_64/
    CentOS-7-Plus: http://mirror.centos.org/centos/7/plus/x86_64/

- name: Run reposync 
  command: cobbler reposync &;disown
  async: 45
  poll: 0
